spring:
    application:
        name: spring-boot-redis
    cache:
        type: redis
        redis:
            time-to-live: 60000
    redis:
        host: localhost
        port: 6379

cache-ttl:
    cache-cat-one-ttl-in-min: 5